package org.stellarproximology.trident;
import android.accessibilityservice.*;import android.graphics.Path;import android.os.Bundle;import android.view.accessibility.*;import org.json.*;import java.util.*;
public final class TridentAccessibilityService extends AccessibilityService{
 private static volatile TridentAccessibilityService instance; public static TridentAccessibilityService getInstance(){return instance;}
 protected void onServiceConnected(){instance=this;} public void onAccessibilityEvent(AccessibilityEvent e){} public void onInterrupt(){} public void onDestroy(){instance=null;super.onDestroy();}
 public boolean tap(float x,float y){Path p=new Path();p.moveTo(x,y);return dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(p,0,70)).build(),null,null);}
 public boolean swipe(float x1,float y1,float x2,float y2,long ms){Path p=new Path();p.moveTo(x1,y1);p.lineTo(x2,y2);return dispatchGesture(new GestureDescription.Builder().addStroke(new GestureDescription.StrokeDescription(p,0,Math.max(120,ms))).build(),null,null);}
 public boolean global(String a){if(a==null)return false;switch(a.toUpperCase()){case"BACK":return performGlobalAction(GLOBAL_ACTION_BACK);case"HOME":return performGlobalAction(GLOBAL_ACTION_HOME);case"RECENTS":return performGlobalAction(GLOBAL_ACTION_RECENTS);case"NOTIFICATIONS":return performGlobalAction(GLOBAL_ACTION_NOTIFICATIONS);default:return false;}}
 public boolean clickText(String q){if(q==null||q.trim().isEmpty())return false;AccessibilityNodeInfo r=target();if(r==null)return false;Deque<AccessibilityNodeInfo>d=new ArrayDeque<>();d.add(r);while(!d.isEmpty()){AccessibilityNodeInfo n=d.remove();String t=String.valueOf(n.getText()),c=String.valueOf(n.getContentDescription());if(t.toLowerCase().contains(q.toLowerCase())||c.toLowerCase().contains(q.toLowerCase())){AccessibilityNodeInfo x=n;while(x!=null&&!x.isClickable())x=x.getParent();if(x!=null&&x.performAction(AccessibilityNodeInfo.ACTION_CLICK))return true;}for(int i=0;i<n.getChildCount();i++){AccessibilityNodeInfo z=n.getChild(i);if(z!=null)d.add(z);}}return false;}
 public boolean setText(String t){AccessibilityNodeInfo r=target();if(r==null)return false;AccessibilityNodeInfo f=r.findFocus(AccessibilityNodeInfo.FOCUS_INPUT);if(f==null||!f.isEditable())return false;Bundle b=new Bundle();b.putCharSequence(AccessibilityNodeInfo.ACTION_ARGUMENT_SET_TEXT_CHARSEQUENCE,t==null?"":t);return f.performAction(AccessibilityNodeInfo.ACTION_SET_TEXT,b);}
 public JSONObject snapshot(){JSONObject o=new JSONObject();try{AccessibilityNodeInfo r=target();o.put("ok",r!=null);if(r!=null){o.put("packageName",String.valueOf(r.getPackageName()));o.put("className",String.valueOf(r.getClassName()));}}catch(Exception ignored){}return o;}
 private AccessibilityNodeInfo target(){List<AccessibilityWindowInfo>w=getWindows();if(w!=null)for(int i=w.size()-1;i>=0;i--){AccessibilityNodeInfo r=w.get(i).getRoot();if(r!=null&&(r.getPackageName()==null||!getPackageName().contentEquals(r.getPackageName())))return r;}return getRootInActiveWindow();}
}